// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TierList.Data;

#nullable disable

namespace TierList.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260817124509_AddTierIdToItemField")]
    partial class AddTierIdToItemField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("TierList.Models.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("TierContainerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TierId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TierContainerId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("TierList.Models.Tier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Level")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxItems")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TierContainerId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TierContainerId");

                    b.ToTable("Tiers");
                });

            modelBuilder.Entity("TierList.Models.TierContainer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TierContainers");
                });

            modelBuilder.Entity("TierList.Models.Item", b =>
                {
                    b.HasOne("TierList.Models.TierContainer", "TierContainer")
                        .WithMany("Items")
                        .HasForeignKey("TierContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TierContainer");
                });

            modelBuilder.Entity("TierList.Models.Tier", b =>
                {
                    b.HasOne("TierList.Models.TierContainer", "TierContainer")
                        .WithMany("Tiers")
                        .HasForeignKey("TierContainerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TierContainer");
                });

            modelBuilder.Entity("TierList.Models.TierContainer", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("Tiers");
                });
#pragma warning restore 612, 618
        }
    }
}
